config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations' }

  resources :designs do
    member do
      put 'like', to: 'designs#upvote'
    end
  end

  resources :products do
    resources :order_items, only: [:create, :destroy]
  end

  resources :articles do
    member do
      put 'like', to: 'articles#upvote'
    end
  end

  resources :addresses
  resources :orders, only: [:index, :show]

  root to: 'home#index'

  get 'users/:id', to: 'users#show', as: :user
  get 'users/:id/designs/', to: 'users#design', as: :user_designs
  get 'users/:id/orders/', to: 'users#order', as: :user_orders
  get 'users/:id/content/', to: 'users#content', as: :user_content
  get 'users/:id/address/', to: 'addresses#index', as: :user_address

  get '/users', to: 'users#index', as: :users_default
  get '/leaderboard', to: 'home#leaderboard'
  get '/competition', to: 'home#competition'
  get '/contact', to: 'home#contact', as: :contact_us
  post '/contact', to: 'home#contact_us', as: :message
  get '/add-to-competition/:id', to: 'designs#add_to_competition'

  # These are static pages, not necessarily having a controller method for each:
  get '/themes', to: 'home#themes', as: :themes
  get '/guide', to: 'home#guide', as: :guide
  get '/about', to: 'home#about', as: :about
  get '/faq', to: 'home#faq', as: :faq
  get '/privacy', to: 'home#privacy', as: :privacy

  post '/checkout', to: 'orders#checkout', as: :checkout
  post 'orders/shipping/:id', to: 'orders#shipping', as: :shipping
  get 'orders/payment/:id', to: 'orders#payment', as: :payment
end

app/models/design.rb
class Design < ApplicationRecord

  belongs_to :user
  acts_as_votable

  mount_uploader :image, ImageUploader

  mount_uploader :first_garment_design, ImageUploader
  mount_uploader :second_garment_design, ImageUploader
  mount_uploader :third_garment_design, ImageUploader

  mount_uploader :first_garment_model_design, ImageUploader
  mount_uploader :second_garment_model_design, ImageUploader
  mount_uploader :third_garment_model_design, ImageUploader

  mount_uploader :first_garment_print_design, ImageUploader
  mount_uploader :second_garment_print_design, ImageUploader
  mount_uploader :third_garment_print_design, ImageUploader

  mount_uploader :first_garment_technical_design, ImageUploader
  mount_uploader :second_garment_technical_design, ImageUploader
  mount_uploader :third_garment_technical_design, ImageUploader

  validates :user, presence: true

  # image validations:

  validates :image, presence: true

  validates :first_garment_design, presence: true
  validates :second_garment_design, presence: true
  validates :third_garment_design, presence: true

  validates :first_garment_print_design, presence: true
  validates :second_garment_print_design, presence: true
  validates :third_garment_print_design, presence: true

  validates :first_garment_model_design, presence: true
  validates :second_garment_model_design, presence: true
  validates :third_garment_model_design, presence: true

  validates :first_garment_technical_design, presence: true
  validates :second_garment_technical_design, presence: true
  validates :third_garment_technical_design, presence: true

  # description validations:

  validates :image_desc, presence: true
  validates :first_garment_desc, presence: true
  validates :second_garment_desc, presence: true
  validates :third_garment_desc, presence: true

  before_validation :for_competition_default_value
  before_validation :competition_default_value

  def self.for_competition
    where(for_competition: true)
  end

  def in_competition?
    competition.present?
  end

  def for_competition_default_value
    if self.for_competition.nil?
      self.for_competition = false
    end
  end

  def competition_default_value
    if self.competition.nil?
      self.competition = false
    end
  end

end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController

  ARTICLES_PER_PAGE = 4

  before_action :authenticate_user!, except: [:index, :competition]

  def index
  end

  def new
    @design = Design.new
  end

  def create
    @design = Design.new(design_params)
    @design.user = current_user

    if @design.save
      render 'success'
    else
      render 'new'
    end
  end

  def success
  end

  def show
    @design = Design.find(params[:id])
    @other_designs = Design.where.not(id: @design.id).page(params[:page]).per(ARTICLES_PER_PAGE)
  end

  def update
    @design = Design.where(user: current_user).find(params[:id])
    if @design.update(design_params)
      redirect_to @design
    else
      render 'edit'
    end
  end

  def edit
    @design = Design.find(params[:id])
    unless @design.user == current_user
      redirect_to @design
    end
  end

  def add_to_competition
    design = Design.find(params[:id])
    design.competition = true
    if design.save
      flash[:notice] = 'Your design has been submitted for review!'
    else
      flash[:notice] = 'Sorry, there has been a problem when processing your design.'
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @design = Design.find(params[:id])
    if current_user == @design.user
      @design.destroy
      flash['notice'] = 'Successfully deleted.'
    else
      flash['notice'] = 'You do not have the permission to delete this post'
    end
    redirect_to designs_path
  end

  def upvote
    design = Design.find(params[:id])
    if current_user.voted_for? design
      flash[:error] = 'You already liked this design!'
    else
      design.upvote_by current_user
      first_vote(design)
      flash[:notice] = 'You have successfully voted!'
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def design_params
    params.require(:design).permit(:image, :image_desc, :first_garment_desc, :second_garment_desc,
                                   :third_garment_desc, :first_garment_print_design, :second_garment_print_design, :third_garment_print_design,
                                   :first_garment_design, :second_garment_design, :third_garment_design, :first_garment_model_design,
                                   :second_garment_model_design, :third_garment_model_design, :competition, :first_garment_technical_design,
                                   :second_garment_technical_design, :third_garment_technical_design)
  end

  def first_vote(design)
    if design.get_upvotes.size == 1
      UserMailer.first_vote_notification(design).deliver
    end
  end

end

app/views/designs/_new_design.html.erb
<%= form_for(@design, html: { method: :post, class: "form formAdd", multipart: true }) do |f| %>
	<!-- Section tittle -->
  <div class="blog">
      <div class="blog__wrapper">
          <div class="blog__intro">
              <div class="blog__heading">Total look</div>
          </div>
          <p id="fontSize" >Upload your total look sketch below</p>
      </div>
  </div>
	<!-- End Section tittle -->

	<!-- Form additional information start -->
	<div class="wrapper" id="formAdd">
    <div class="input-wb">
      <%= f.label :image, 'Upload "Total look" File' %>
			<%= f.file_field :image, class: "form__input" %>
    </div>
    <div class="input-w">
      <%= f.label :image_desc, "Explain us your design concept. What did you get inspired by?" %>
			<%= f.text_area :image_desc, class: "form__input", rows: "8", placeholder: "E.g The theme was set around winter that's why I used gray and blue colors. I tried to use garments that are warm and used leaves for the print design." %>
    </div>
	</div>
	<!-- End Form additional information start -->


	<!-- Section tittle -->
	  <div class="blog">
	      <div class="blog__wrapper">
	          <div class="blog__intro">
	              <div class="blog__heading">flat pattern drawing garment 1</div>
	          </div>
	          <p id="fontSize" >Upload your falt pattern drawing garment 1 below</p>
	      </div>
	  </div>
	<!-- End Section tittle -->

	<!-- Form additional information start -->
	<div class="wrapper" id="formAdd">
	        <div class="input-wb">
			      <%= f.label :first_garment_model_design, '"Model Picture" File' %>
						<%= f.file_field :first_garment_model_design, class: "form__input" %>
	        </div>

	        <div class="input-wb">
			      <%= f.label :first_garment_print_design, '"Print design" File' %>
						<%= f.file_field :first_garment_print_design, class: "form__input" %>
	        </div>

	        <div class="input-wb">
			      <%= f.label :first_garment_technical_design, 'Optional "Technical Sheet" File' %>
						<%= f.file_field :first_garment_technical_design, class: "form__input" %>
	        </div>

	        <div class="input-w">
			      <%= f.label :first_garment_desc, "Description of the garment with its technical explanation and  materials description." %>
						<%= f.text_area :first_garment_desc, class: "form__input", rows: "8", placeholder: "E.g The theme was set around winter that's why I used gray and blue colors. I tried to use garments that are warm and used leaves for the print design." %>	          
	        </div>
	</div>
	<!-- End Form additional information start -->

	<!-- Section tittle -->
	  <div class="blog">
	      <div class="blog__wrapper">
	          <div class="blog__intro">
	              <div class="blog__heading">flat pattern drawing garment 2</div>
	          </div>
	          <p id="fontSize" >Upload your falt pattern drawing garment 2 below</p>
	      </div>
	  </div>
	<!-- End Section tittle -->

	<!-- Form additional information start -->
	<div class="wrapper" id="formAdd">
    <div class="input-wb">
      <%= f.label :second_garment_model_design, '"Model Picture 2" File' %>
			<%= f.file_field :second_garment_model_design, class: "form__input" %>
    </div>

    <div class="input-wb">
      <%= f.label :second_garment_print_design, '"Print design 2" File' %>
			<%= f.file_field :second_garment_print_design, class: "form__input" %>
    </div>

    <div class="input-wb">
      <%= f.label :second_garment_technical_design, 'Optional "Technical Sheet" File' %>
			<%= f.file_field :second_garment_technical_design, class: "form__input" %>
    </div>

    <div class="input-w">
      <%= f.label :second_garment_desc, "Description of the garment with its technical explanation and  materials description." %>
			<%= f.text_area :second_garment_desc, class: "form__input", rows: "8", placeholder: "E.g The theme was set around winter that's why I used gray and blue colors. I tried to use garments that are warm and used leaves for the print design." %>	          
    </div>
	</div>
	<!-- End Form additional information start -->

	<!-- Section tittle -->
	 <div class="blog">
	     <div class="blog__wrapper">
	         <div class="blog__intro">
	             <div class="blog__heading">flat pattern drawing garment 3</div>
	         </div>
	         <p id="fontSize" >Upload your falt pattern drawing garment 3 below</p>
	     </div>
	 </div>
	<!-- End Section tittle -->

	<!-- Form additional information start -->
	<div class="wrapper" id="formAdd">
    <div class="input-wb">
      <%= f.label :third_garment_model_design, '"Model Picture 3" File' %>
			<%= f.file_field :third_garment_model_design, class: "form__input" %>
    </div>

    <div class="input-wb">
      <%= f.label :third_garment_print_design, '"Print design 3" File' %>
			<%= f.file_field :third_garment_print_design, class: "form__input" %>
    </div>

    <div class="input-wb">
      <%= f.label :third_garment_technical_design, 'Optional "Technical Sheet" File' %>
			<%= f.file_field :third_garment_technical_design, class: "form__input" %>
    </div>

    <div class="input-w">
      <%= f.label :third_garment_desc, "Description of the garment with its technical explanation and  materials description." %>
			<%= f.text_area :third_garment_desc, class: "form__input", rows: "8", placeholder: "E.g The theme was set around winter that's why I used gray and blue colors. I tried to use garments that are warm and used leaves for the print design." %>	          
    </div>
	</div>
	<!-- Button -->
	<div class="wrapper">
	  <%= f.submit "Save & Continue", class: "button button_blue"%>
	</div>

	<!-- End Form additional information start -->
<% end %>

app/views/designs/index.html.erb
<!-- Section tittle -->
<h1 class="title_h1_description">Become a Lumumba Designer</h1>
<p class="page-description">
  Become a Lumumba Designer Applying for the competition is easy and fun. Create and design a great outfit that people will love.
  You can get inspiration from the Theme page. The guidelines are found in the <a href="<%= guide_path %>">Design Guide</a>
</p>
<!-- End Section tittle -->

<!-- Section Icon and small description become -->
<div class="wrapper">
  <center>
     <ul class="become__list">
        <li class="become__item_3">
           <div class="columns__content">
                <%= image_tag "design.svg", id: "svg_img" %>
                <p class="p_become">Design 1 outfit after reading the competition <a href="<%= guide_path %>">Designer Guide</a><p>
           </div>
        </li>
         <li class="become__item_3">
           <div class="columns__content">
               <%= image_tag "upload.svg", id: "svg_img" %>
               <p class="p_become">Upload the files and fill the form<p>
           </div>
        </li>
         <li class="become__item_3">
           <div class="columns__content">
               <%= image_tag "welcome.svg", id: "svg_img" %>
               <p class="p_become">Welcome, Lumumba designer!<p>
           </div>
        </li>
     </ul>
   </center>

   <div class="buttons_become">
     <a  href="<%= guide_path %>" class="button button_orange button_become_left">
         <div class="button__text">Design Guide</div>
     </a>
     <a href="<%= new_design_path %>" class="button button_orange button_become_right">
         <div class="button__text">Get Started</div>
     </a>
   </div>
 </div>
<!-- End Section Icon and small description become -->

app/views/designs/new.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $('#model-design-view').hide();
    $('#hideshow').on('click', function(event) {
      $('#model-design-view').toggle('show');
    });
  });
</script>


<%= form_for :design, url: designs_path, html: {class: "form ", multipart: true } do |f| %>

  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@design.errors.count, "error") %> prohibited
        this design from being saved:
      </h2>
      <ul>
        <% @design.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="dummy__wrapper" id="designs">
    <!-- Section tittle -->
    <div class="blog">
        <div class="blog__wrapper">
            <div class="blog__intro">
                <div class="title_h1_cart">Total Look</div>
            </div>
            <p id="fontSize" >Upload your total look sketch below</p>
        </div>
    </div>
    <!-- End Section tittle -->

    <!-- Form additional information start -->
    <div class="wrapper" id="formAdd">
      <div class="input-wb">
        <%= f.label :image, 'Upload "Total look" File' %>
        <%= f.file_field :image, class: "form__input" %>
      </div>
      <div class="input-w">
        <%= f.label :image_desc, "Explain us your design concept. What did you get inspired by?" %>
        <%= f.text_area :image_desc, class: "form__input", rows: "8", placeholder: "E.g The theme was set around winter that's why I used gray and blue colors. I tried to use garments that are warm and used leaves for the print design." %>
      </div>
    </div>
    <!-- End Form additional information start -->


    <!-- Section tittle -->
      <div class="blog">
          <div class="blog__wrapper">
              <div class="blog__intro">
                  <div class="title_h1_cart">Flat Pattern Drawing Garment 1</div>
              </div>
              <p id="fontSize" >Upload your flat pattern drawing garment 1 below</p>
          </div>
      </div>
    <!-- End Section tittle -->

    <!-- Form additional information start -->
    <div class="wrapper" id="formAdd">
      <div class="input-wb">
        <%= f.label :first_garment_design, '"Garment 1" File' %>
        <%= f.file_field :first_garment_design, class: "form__input" %>
      </div>

      <div class="input-wb">
        <%= f.label :first_garment_print_design, '"Print design" File' %>
        <%= f.file_field :first_garment_print_design, class: "form__input" %>
      </div>

      <div class="input-wb">
        <%= f.label :first_garment_technical_design, 'Optional "Technical Sheet" File' %>
        <%= f.file_field :first_garment_technical_design, class: "form__input" %>
      </div>

      <div class="input-w">
        <%= f.label :first_garment_desc, "Description of the garment with its technical explanation and  materials description." %>
        <%= f.text_area :first_garment_desc, class: "form__input", rows: "8", placeholder: "E.g The theme was set around winter that's why I used gray and blue colors. I tried to use garments that are warm and used leaves for the print design." %>
      </div>
    </div>
    <!-- End Form additional information start -->

    <!-- Section tittle -->
      <div class="blog">
          <div class="blog__wrapper">
              <div class="blog__intro">
                  <div class="title_h1_cart">Flat Pattern Drawing Garment 2</div>
              </div>
              <p id="fontSize" >Upload your flat pattern drawing garment 2 below</p>
          </div>
      </div>
    <!-- End Section tittle -->

    <!-- Form additional information start -->
    <div class="wrapper" id="formAdd">
      <div class="input-wb">
        <%= f.label :second_garment_design, '"Garment 2" File' %>
        <%= f.file_field :second_garment_design, class: "form__input" %>
      </div>

      <div class="input-wb">
        <%= f.label :second_garment_print_design, '"Print design 2" File' %>
        <%= f.file_field :second_garment_print_design, class: "form__input" %>
      </div>

      <div class="input-wb">
        <%= f.label :second_garment_technical_design, 'Optional "Technical Sheet" File' %>
        <%= f.file_field :second_garment_technical_design, class: "form__input" %>
      </div>

      <div class="input-w">
        <%= f.label :second_garment_desc, "Description of the garment with its technical explanation and  materials description." %>
        <%= f.text_area :second_garment_desc, class: "form__input", rows: "8", placeholder: "E.g The theme was set around winter that's why I used gray and blue colors. I tried to use garments that are warm and used leaves for the print design." %>
      </div>
    </div>
    <!-- End Form additional information start -->

    <!-- Section tittle -->
     <div class="blog">
         <div class="blog__wrapper">
             <div class="blog__intro">
                 <div class="title_h1_cart">Flat Pattern Drawing Garment 3</div>
             </div>
             <p id="fontSize" >Upload your flat pattern drawing garment 3 below</p>
         </div>
     </div>
    <!-- End Section tittle -->

    <!-- Form additional information start -->
    <div class="wrapper" id="formAdd">
      <div class="input-wb">
        <%= f.label :third_garment_design, '"Garment 3" File' %>
        <%= f.file_field :third_garment_design, class: "form__input" %>
      </div>

      <div class="input-wb">
        <%= f.label :third_garment_print_design, '"Print design 3" File' %>
        <%= f.file_field :third_garment_print_design, class: "form__input" %>
      </div>

      <div class="input-wb">
        <%= f.label :third_garment_technical_design, 'Optional "Technical Sheet" File' %>

        <%= f.file_field :third_garment_technical_design, class: "form__input" %>

      </div>

      <div class="input-w">
        <%= f.label :third_garment_desc, "Description of the garment with its technical explanation and  materials description." %>
        <%= f.text_area :third_garment_desc, class: "form__input", rows: "8", placeholder: "E.g The theme was set around winter that's why I used gray and blue colors. I tried to use garments that are warm and used leaves for the print design." %>
      </div>
    </div>

    <!-- Button to toggle model-design upload view-->
    <div class="wrapper">
      <input type='button' id='hideshow' value='Add Model Design' class="button button_orange">
    </div>
    <!-- End of Button to toggle model-design upload view -->

    <!-- Model design upload view -->
    <div id='model-design-view'>
      <!-- Section tittle -->
      <div class="blog">
          <div class="blog__wrapper">
              <div class="blog__intro">
                  <div class="title_h1_cart">Model Design look</div>
              </div>
              <p id="fontSize" >Upload your model design pictures below</p>
          </div>
      </div>
      <!-- End Section tittle -->

      <div class="input-wb">
        <%= f.label :first_garment_model_design, 'First Garment Model Picture' %>
        <%= f.file_field :first_garment_model_design, class: "form__input" %>
      </div>

      <div class="input-wb">
        <%= f.label :second_garment_model_design, 'Second Garment Model Picture' %>
        <%= f.file_field :second_garment_model_design, class: "form__input" %>
      </div>

      <div class="input-wb">
        <%= f.label :third_garment_model_design, 'Third Garment Model Picture' %>
        <%= f.file_field :third_garment_model_design, class: "form__input" %>
      </div>
    </div><br>
    <!-- End of Model design upload view -->
    <div class="text-right">
      <%= f.label :competition, 'Include Design in ongoing competition' %>
      <%= f.check_box :competition, class: "form__input" %>
    </div>
    <br>
    <!-- Button -->
    <div class="wrapper">
      <%= f.submit "Save & Continue", class: "button button_orange big button_become_right"%>
      <%= link_to 'Back', designs_path, class: "button button_orange button_become_left" %>
    </div>

    <!-- End Form additional information start -->
  <% end %>

  <br>


</div>

app/views/designs/show.html.erb
<div class="participant">
    <div class="participant__wrapper">
        <div class="participant__photo-wrapper"><div class="participant__photo" style="background-image: url(<%= asset_path @design.image.url %>)" ></div></div>
        <div class="participant__info">
            <div class="participant__desc-title">Description</div>
            <p class="participant__desc"><%= @design.image_desc%></p>
            <div class="participant__actions">

                <div class="participant__action">
                    <svg width="22" height="20" viewBox="0 0 22 20" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                        <title>Page 1</title>
                        <defs>
                            <path id="like-path" d="M21.97 0H0v19.957h21.97V0z" />
                        </defs>
                        <g fill="none" fill-rule="evenodd">
                            <path d="M1.005 5.418c-.008 1.135.215 1.885.5 2.62.35.89.806 1.733 1.315 2.547.997 1.596 2.168 3.062 3.473 4.428 1.38 1.446 2.88 2.757 4.588 3.83.08.05.134.044.21-.003.968-.603 1.868-1.293 2.722-2.04 1.56-1.364 2.955-2.877 4.184-4.533 1.035-1.394 1.955-2.852 2.56-4.48.19-.513.34-1.037.39-1.58.082-.882-.075-1.73-.494-2.517-.773-1.456-1.988-2.344-3.646-2.64-.766-.138-1.52-.084-2.265.135-1.064.312-1.93.903-2.586 1.778-.31.414-.59.85-.882 1.274-.083.12-.093.12-.172.005-.238-.347-.472-.697-.713-1.042-.9-1.287-2.133-2.032-3.728-2.197-.82-.85-1.62.02-2.367.343-1.954.846-2.966 2.337-3.088 4.072m20.964.295c-.034.97-.22 1.688-.48 2.392-.567 1.553-1.41 2.963-2.373 4.308-1.434 2.01-3.1 3.817-5 5.42-.84.708-1.725 1.36-2.67 1.932-.128.077-.27.132-.412.186-.04.017-.098 0-.143-.016-.327-.112-.606-.308-.89-.495-2.034-1.34-3.792-2.973-5.38-4.788C3.4 13.256 2.31 11.77 1.416 10.15 1.002 9.4.64 8.63.373 7.818.14 7.11-.037 6.386.007 5.636.147 3.31 1.303 1.622 3.424.574 4.338.122 5.33-.056 6.35.02c1.887.137 3.4.954 4.525 2.443.01.013.016.026.026.038.077.104.082.1.165.003.26-.3.506-.62.795-.893.71-.67 1.55-1.125 2.5-1.385.805-.22 1.622-.29 2.444-.16 2.136.337 3.688 1.458 4.626 3.367.387.788.544 1.627.54 2.28" fill="currentColor" />
                        </g>
                    </svg>
                </div>

                <div class="participant__action">  <%= @design.get_upvotes.size %></div>
            </div>
            <div class="participant__social-title">Share</div>
            <div class="participant__social"><a class="participant__social-link" href="https://www.facebook.com/XXX" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i> </a><a class="participant__social-link" href="https://twitter.com/XXX" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i> </a><a class="participant__social-link" href="https://plus.google.com/XXX" target="_blank"><i class="fa fa-google-plus" aria-hidden="true"></i> </a><a class="participant__social-link" href="https://pinterest.com/XXX" target="_blank"><i class="fa fa-pinterest-p" aria-hidden="true"></i> </a><a class="participant__social-link" href="https://www.instagram.com/XXX" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></div>
            <div class="participant__designer-title">Designer</div>
            <div class="participant__designer-block"><div class="participant__designer-photo" style="background-image: url(<%= asset_path(image) if image = @design.user.image %>)" ></div>
                <div class="participant__designer-info">
                    <div class="participant__designer-name"><%= @design.user.first_name%> <%= @design.user.last_name%></div>
                    <div class="participant__designer-location"><%= @design.user.location%> </div>
                </div>
                <div class="participant__designer-sign"><%= @design.user.description %></div>
            </div>
        </div>
    </div>
</div>
<!-- Participant finish -->
<!-- Recommended designers start -->
<hr>
<h2>More from this designer</h2>
<div class="contestants">
    <div class="contestants__wrapper">
        <ul class="contestants__list">
            <% @other_designs.each do |design| %>
            <li class="contestants__item">
                <a class="contestants__link" href="javascript:;"><img class="contestants__photo" style="background-image: url(<%= asset_path design.image.url %>)"></a>
                <div class="contestants__info">
                    <div class="contestants__author">By <a class="contestants__author-link" href="javascript:;"><%= design.user.first_name %></a></div>
                    <div class="contestants__action">
                        <%= link_to like_design_path(design), method: :put do %>
                        <svg width="22" height="20" viewBox="0 0 22 20" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                            <title>Page 1</title>
                            <defs>
                                <path id="like-path" d="M21.97 0H0v19.957h21.97V0z" />
                            </defs>
                            <g fill="none" fill-rule="evenodd">
                                <path d="M1.005 5.418c-.008 1.135.215 1.885.5 2.62.35.89.806 1.733 1.315 2.547.997 1.596 2.168 3.062 3.473 4.428 1.38 1.446 2.88 2.757 4.588 3.83.08.05.134.044.21-.003.968-.603 1.868-1.293 2.722-2.04 1.56-1.364 2.955-2.877 4.184-4.533 1.035-1.394 1.955-2.852 2.56-4.48.19-.513.34-1.037.39-1.58.082-.882-.075-1.73-.494-2.517-.773-1.456-1.988-2.344-3.646-2.64-.766-.138-1.52-.084-2.265.135-1.064.312-1.93.903-2.586 1.778-.31.414-.59.85-.882 1.274-.083.12-.093.12-.172.005-.238-.347-.472-.697-.713-1.042-.9-1.287-2.133-2.032-3.728-2.197-.82-.085-1.62.02-2.367.343-1.954.846-2.966 2.337-3.088 4.072m20.964.295c-.034.97-.22 1.688-.48 2.392-.567 1.553-1.41 2.963-2.373 4.308-1.434 2.01-3.1 3.817-5 5.42-.84.708-1.725 1.36-2.67 1.932-.128.077-.27.132-.412.186-.04.017-.098 0-.143-.016-.327-.112-.606-.308-.89-.495-2.034-1.34-3.792-2.973-5.38-4.788C3.4 13.256 2.31 11.77 1.416 10.15 1.002 9.4.64 8.63.373 7.818.14 7.11-.037 6.386.007 5.636.147 3.31 1.303 1.622 3.424.574 4.338.122 5.33-.056 6.35.02c1.887.137 3.4.954 4.525 2.443.01.013.016.026.026.038.077.104.082.1.165.003.26-.3.506-.62.795-.893.71-.67 1.55-1.125 2.5-1.385.805-.22 1.622-.29 2.444-.16 2.136.337 3.688 1.458 4.626 3.367.387.788.544 1.627.54 2.28" fill="currentColor" />
                            </g>
                        </svg>
                        <% end %>
                    </div>
                    <div class="contestants__action">
                    <p></p>
                    </div>
                </div>
            </li>
            <% end %>
        </ul>
        <%= paginate @other_designs %>
    </div>
</div>

app/views/designs/success.html.erb
<!-- Section tittle -->
<h1 class="title_h1">Thank you for becoming a lumumba designer</h1>
<!-- End Section tittle -->

<!-- Section Icon and small description become -->
<div class="wrapper">
  <center>
     <ul class="become__list">
        <li class="become__item_1">
           <div class="columns__content">
            <%= image_tag "welcome.svg"%>
                <h4 class="h_become_2"> Share your design </h4>
                <p class="p_become_1">Thank you for taking part in the lumumba design competition. To increase your chance of winning invite your gmail contacts or share your design on facebook.<p>
           </div>
        </li>
     </ul>
     <a id="floatRight" class="shareButtons" href="#" >
       <div class="button-social2 facebook">
         <i class="fa fa-facebook" aria-hidden="true"></i> <spam class="social-text">Sign up using facebook</spam>
       </div>
     </a>
     <a id="floatLeft" class="shareButtons" href="#" >
       <div class="button-social2 google">
         <i class="fa fa-google-plus" aria-hidden="true"></i> <spam class="social-text">Invite Gmail Contacts</spam>
       </div>
     </a>

   </center>
 </div>
<!-- End Section Icon and small description become -->