config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations' }

  resources :designs do
    member do
      put 'like', to: 'designs#upvote'
    end
  end

  resources :products do
    resources :order_items, only: [:create, :destroy]
  end

  resources :articles do
    member do
      put 'like', to: 'articles#upvote'
    end
  end

  resources :addresses
  resources :orders, only: [:index, :show]

  root to: 'home#index'

  get 'users/:id', to: 'users#show', as: :user
  get 'users/:id/designs/', to: 'users#design', as: :user_designs
  get 'users/:id/orders/', to: 'users#order', as: :user_orders
  get 'users/:id/content/', to: 'users#content', as: :user_content
  get 'users/:id/address/', to: 'addresses#index', as: :user_address

  get '/users', to: 'users#index', as: :users_default
  get '/leaderboard', to: 'home#leaderboard'
  get '/competition', to: 'home#competition'
  get '/contact', to: 'home#contact', as: :contact_us
  post '/contact', to: 'home#contact_us', as: :message
  get '/add-to-competition/:id', to: 'designs#add_to_competition'

  # These are static pages, not necessarily having a controller method for each:
  get '/themes', to: 'home#themes', as: :themes
  get '/guide', to: 'home#guide', as: :guide
  get '/about', to: 'home#about', as: :about
  get '/faq', to: 'home#faq', as: :faq
  get '/privacy', to: 'home#privacy', as: :privacy

  post '/checkout', to: 'orders#checkout', as: :checkout
  post 'orders/shipping/:id', to: 'orders#shipping', as: :shipping
  get 'orders/payment/:id', to: 'orders#payment', as: :payment
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  mount_uploader :image, ImageUploader
  acts_as_votable

  validates :title, presence: true, length: { minimum: 20 }
  validates :description, presence: true, length: { minimum: 500 }
  validates :image, presence: true
  validates :user, presence: true

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  ARTICLES_PER_PAGE = 5

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all.page(params[:page]).per(ARTICLES_PER_PAGE)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    @article.author = current_user.to_s

    if @article.save
      flash['notice'] = 'Post successfully created.'
      article_notification(@article)
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def upvote
    article = Article.find(params[:id])
    if current_user.voted_for? article
      flash[:error] = 'You already liked this article!'
    else
      article.upvote_by current_user
      flash[:notice] = 'Liked!'
      vote_notification article
    end
    redirect_back(fallback_location: root_path)
  end

  def update
    @article = Article.where(user: current_user.id).find(params[:id])

    if @article.update(article_params)
      flash[:notice] = 'Post successfully updated.'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def edit
    @article = Article.find(params[:id])
    unless current_user == @article.user
      redirect_to @article
      return
    end
  end

  def destroy
    article = Article.find(params[:id])
    if article.user == current_user
      article.destroy
      flash['notice'] = 'Successfully deleted this post.'
    else
      flash['notice'] = 'You do not hae the permission to delete this post'
    end
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, :image)
  end

  def vote_notification(article)
    message = "Your blogpost was liked by #{current_user.first_name}. View it [here](#{article_path(article)})"
    notice = Notification.new(notice: message, user: current_user)
    save_notification(notice)
  end

  def article_notification(article)
    message = "You created a blogpost. View it [here](#{article_path(article)})"
    notice = Notification.new(notice: message, user: current_user)
    save_notification(notice)
  end

  def save_notification(notification)
    notification.save
    unless notification.persisted?
      message = "Notification failed: #{notification.errors.messages}"
      Rollbar.warn message
      Rails.logger.warn message
    end
  end

end

app/views/articles/_add_blogpost.html.erb
<%= form_for :article, url: articles_path, html: {class: "form ", multipart: true } do |f| %>
  <p class="form__group">
    <%= f.label :title, "Enter the Title of your post" %><br>
    <%= f.text_field :title, class: "form__input" %>
  </p><br>
 
  <p class="form__group">
    <%= f.label :description, "Enter a description for your post" %><br>
    <%= f.text_area :description, class: "form__input", placeholder: "Enter a description"%>
  </p><br>
    <%= f.label :image, "Upload an image for your post"%>
    <%= f.file_field :image, class: "form__input" %>
  </p> <br>
  <p class="form__group">
    <%= f.submit "Post Blog", class: "button button_blue"%>
  </p>
<% end %>

app/views/articles/_blogpost_form.html.erb
<%= form_for :article, html: {class: "form ", multipart: true } do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p class="form__group">
    <%= f.label :title, "Enter the Title of your post" %><br>
    <%= f.text_field :title, class: "form__input" %>
  </p><br>
 
  <p class="form__group">
    <%= f.label :description, "Enter a description for your post" %><br>
    <%= f.text_area :description, class: "form__input", placeholder: "Enter a description"%>
  </p><br>
    <%= f.label :image, "Upload an image for your post"%>
    <%= f.file_field :image, class: "form__input" %>
  </p> <br>
  <p class="form__group">
    <%= f.submit "Post Blog", class: "button button_blue"%>
  </p>
<% end %>


<%= link_to 'Back', articles_path %>

app/views/articles/_edit_blogpost_form.html.erb
<div class="dummy">
  <div class="dummy__wrapper">
    <%= form_for :article,url: articles_path(@article), html: {class: "form ", multipart: true } do |f| %>

      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <p class="form__group">
        <%= f.label :title, "Enter the Title of your post" %><br>
        <%= f.text_field :title, class: "form__input" %>
      </p><br>

      <p class="form__group">
        <%= f.label :description, "Enter a description for your post" %><br>
        <%= f.text_area :description, class: "form__input", placeholder: "Enter a description"%>
      </p><br>
        <%= f.label :image, "Upload an image for your post"%>
        <%= f.file_field :image, class: "form__input" %>
        <%= f.hidden_field :image_cache %>
      </p> <br>
      <p class="form__group">
        <%= f.submit "Post Blog", class: "button button_blue"%>
      </p>
    <% end %>

    <br>
    <%= link_to 'Back', articles_path, class: "button button_blue" %>

  </div>
</div>

app/views/articles/_new_blogpost_form.html.erb
<div class="dummy">
  <div class="dummy__wrapper">
    <%= form_for :article, url: articles_path, html: {class: "form ", multipart: true } do |f| %>

      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@article.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <p class="form__group">
        <%= f.label :title, "Enter the Title of your post" %><br>
        <%= f.text_field :title, class: "form__input" %>
      </p><br>

      <p class="form__group">
        <%= f.label :description, "Enter a description for your post" %><br>
        <%= f.text_area :description, class: "form__input", placeholder: "Enter a description"%>
      </p><br>
        <%= f.label :image, "Upload an image for your post"%>
        <%= f.file_field :image, class: "form__input" %>
      </p> <br>
      <p class="form__group">
        <%= f.submit "Post Blog", class: "button button_blue"%>
      </p>
    <% end %>

    <br>
    <%= link_to 'Back', articles_path, class: "button button_blue" %>

  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'edit_blogpost_form' %>

app/views/articles/index.html.erb
<div class="" id="post-list">
    <!-- Top post start -->
    <div class="top-post">
        <div class="top-post__wrapper">
            <div class="top-post__image-wrapper" style="background-image: url(<%= first_article_image_url %>);"></div>
            <div class="top-post__info">
                <div class="top-post__heading">Top post</div>
                <div class="top-post__title"><%= @articles.first.try :title%></div>
                <div class="top-post__author">by </div>
                <div class="top-post__preview"><%= @articles.first.try :description%></div>

            </div>
        </div>
    </div>
    <!-- Top post finish -->

<!-- Blog start -->
<div class="blog" id="posts_display">
    <div class="blog__wrapper">
        <div class="blog__intro">
            <div class="blog__heading">Trending posts</div>
            <div class="blog__button-wrapper">
                <div class="button button_orange">
                  <%= link_to "Post a Blog", new_article_path, class: "button__text", id: "new_link"%>
                </div>
            </div>
        </div>

        <!-- Post contents start -->
        <% if @articles.empty? %>
            <p>Nothing to show</p>
        <% else %>
        <ul class="blog__list">
            <%= paginate @articles %>
            <% @articles.each do |blog|%>
                <li class="blog__item">
                    <div class="blog__image-wrapper" style="background-image: url(<%=  blog.image.url.to_s %>);"></div>
                    <div class="blog__info">
                        <div class="blog__title"><%= blog.title%>                           </div>
                        <div class="blog__author"><%= blog.user.try :last_name %>  <%= blog.user.try :first_name%></div>
                        <div class="blog__preview"><%= blog.description%></div>
                        <div class="blog__date"><%= blog.created_at%></div>

                        <div class="blog__actions">

                            <td><%= link_to 'Continue Reading', article_path(blog), class: "button button_blue blog__button button__text" %></td>
                            <% if current_user.present? && (current_user.id == blog.user.try(:id)) %>
                                <td><%= link_to 'Edit', edit_article_path(blog), class: "button button_blue blog__button button__text" %></td>
                                <td><%= link_to 'Destroy', article_path(blog), method: :delete, data: { confirm: 'Are you sure?' }, class: "button button_blue blog__button button__text" %></td>
                            <% end %>

                            <div class="blog__action">
                                <%= link_to like_article_path(blog), method: :put do %>
                                    <svg width="22" height="20" viewBox="0 0 22 20" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                                        <title>Page 1</title>
                                        <defs>
                                            <path id="like-path" d="M21.97 0H0v19.957h21.97V0z" />
                                        </defs>
                                        <g fill="none" fill-rule="evenodd">
                                            <path d="M1.005 5.418c-.008 1.135.215 1.885.5 2.62.35.89.806 1.733 1.315 2.547.997 1.596 2.168 3.062 3.473 4.428 1.38 1.446 2.88 2.757 4.588 3.83.08.05.134.044.21-.003.968-.603 1.868-1.293 2.722-2.04 1.56-1.364 2.955-2.877 4.184-4.533 1.035-1.394 1.955-2.852 2.56-4.48.19-.513.34-1.037.39-1.58.082-.882-.075-1.73-.494-2.517-.773-1.456-1.988-2.344-3.646-2.64-.766-.138-1.52-.084-2.265.135-1.064.312-1.93.903-2.586 1.778-.31.414-.59.85-.882 1.274-.083.12-.093.12-.172.005-.238-.347-.472-.697-.713-1.042-.9-1.287-2.133-2.032-3.728-2.197-.82-.085-1.62.02-2.367.343-1.954.846-2.966 2.337-3.088 4.072m20.964.295c-.034.97-.22 1.688-.48 2.392-.567 1.553-1.41 2.963-2.373 4.308-1.434 2.01-3.1 3.817-5 5.42-.84.708-1.725 1.36-2.67 1.932-.128.077-.27.132-.412.186-.04.017-.098 0-.143-.016-.327-.112-.606-.308-.89-.495-2.034-1.34-3.792-2.973-5.38-4.788C3.4 13.256 2.31 11.77 1.416 10.15 1.002 9.4.64 8.63.373 7.818.14 7.11-.037 6.386.007 5.636.147 3.31 1.303 1.622 3.424.574 4.338.122 5.33-.056 6.35.02c1.887.137 3.4.954 4.525 2.443.01.013.016.026.026.038.077.104.082.1.165.003.26-.3.506-.62.795-.893.71-.67 1.55-1.125 2.5-1.385.805-.22 1.622-.29 2.444-.16 2.136.337 3.688 1.458 4.626 3.367.387.788.544 1.627.54 2.28" fill="currentColor" />
                                        </g>
                                    </svg>
                                <% end %>
                            </div>

                            <div class="contestants__action blog">

                                  <%= blog.get_upvotes.size %>

                            </div>

                        </div>
                    </div>
                </li>
            <% end %>
            <!-- Post contents finish -->
        </ul>
        <% end %>
    </div>
</div>
<!-- Blog finish -->
</div>
<br><br>
<%= paginate @articles %>

app/views/articles/new.html.erb
<%= render 'new_blogpost_form' %>

app/views/articles/show.html.erb
<div id="articles">
  <div class="dummy" >
    <div class="dummy__wrapper">
      <div class="blog__item">
          <div class="blog__info">
            <div class="blog__image-wrapper" style="background-image: url(<%=  @article.image.url.to_s %>);"></div>
            <div class="blog__details">
              <div class="blog__title"><%= @article.title%> </div>
              <div class="blog__author">By  <%= @article.user.first_name%> <%= @article.user.last_name%> </div>
              <div class="blog__date"><%= @article.created_at.strftime("%dth-%B-%Y")%></div>
            </div>
            <div class="blog__preview"><%= @article.description%></div>
              <div class="blog__actions">
                  <div class="blog__action">
                      <svg width="22" height="20" viewBox="0 0 22 20" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                          <title>Page 1</title>
                          <defs>
                              <path id="like-path" d="M21.97 0H0v19.957h21.97V0z" />
                          </defs>
                          <g fill="none" fill-rule="evenodd">
                              <path d="M1.005 5.418c-.008 1.135.215 1.885.5 2.62.35.89.806 1.733 1.315 2.547.997 1.596 2.168 3.062 3.473 4.428 1.38 1.446 2.88 2.757 4.588 3.83.08.05.134.044.21-.003.968-.603 1.868-1.293 2.722-2.04 1.56-1.364 2.955-2.877 4.184-4.533 1.035-1.394 1.955-2.852 2.56-4.48.19-.513.34-1.037.39-1.58.082-.882-.075-1.73-.494-2.517-.773-1.456-1.988-2.344-3.646-2.64-.766-.138-1.52-.084-2.265.135-1.064.312-1.93.903-2.586 1.778-.31.414-.59.85-.882 1.274-.083.12-.093.12-.172.005-.238-.347-.472-.697-.713-1.042-.9-1.287-2.133-2.032-3.728-2.197-.82-.085-1.62.02-2.367.343-1.954.846-2.966 2.337-3.088 4.072m20.964.295c-.034.97-.22 1.688-.48 2.392-.567 1.553-1.41 2.963-2.373 4.308-1.434 2.01-3.1 3.817-5 5.42-.84.708-1.725 1.36-2.67 1.932-.128.077-.27.132-.412.186-.04.017-.098 0-.143-.016-.327-.112-.606-.308-.89-.495-2.034-1.34-3.792-2.973-5.38-4.788C3.4 13.256 2.31 11.77 1.416 10.15 1.002 9.4.64 8.63.373 7.818.14 7.11-.037 6.386.007 5.636.147 3.31 1.303 1.622 3.424.574 4.338.122 5.33-.056 6.35.02c1.887.137 3.4.954 4.525 2.443.01.013.016.026.026.038.077.104.082.1.165.003.26-.3.506-.62.795-.893.71-.67 1.55-1.125 2.5-1.385.805-.22 1.622-.29 2.444-.16 2.136.337 3.688 1.458 4.626 3.367.387.788.544 1.627.54 2.28" fill="currentColor" />
                          </g>
                      </svg>
                  </div>
                  <div class="blog__action">
                      <%= @article.get_upvotes.size %>
                  </div>
      <!-- Post contents finish -->
                </div>
        </div>
      </div>
    </div>
  </div>
</div>