config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations' }

  resources :designs do
    member do
      put 'like', to: 'designs#upvote'
    end
  end

  resources :products do
    resources :order_items, only: [:create, :destroy]
  end

  resources :articles do
    member do
      put 'like', to: 'articles#upvote'
    end
  end

  resources :addresses
  resources :orders, only: [:index, :show]

  root to: 'home#index'

  get 'users/:id', to: 'users#show', as: :user
  get 'users/:id/designs/', to: 'users#design', as: :user_designs
  get 'users/:id/orders/', to: 'users#order', as: :user_orders
  get 'users/:id/content/', to: 'users#content', as: :user_content
  get 'users/:id/address/', to: 'addresses#index', as: :user_address

  get '/users', to: 'users#index', as: :users_default
  get '/leaderboard', to: 'home#leaderboard'
  get '/competition', to: 'home#competition'
  get '/contact', to: 'home#contact', as: :contact_us
  post '/contact', to: 'home#contact_us', as: :message
  get '/add-to-competition/:id', to: 'designs#add_to_competition'

  # These are static pages, not necessarily having a controller method for each:
  get '/themes', to: 'home#themes', as: :themes
  get '/guide', to: 'home#guide', as: :guide
  get '/about', to: 'home#about', as: :about
  get '/faq', to: 'home#faq', as: :faq
  get '/privacy', to: 'home#privacy', as: :privacy

  post '/checkout', to: 'orders#checkout', as: :checkout
  post 'orders/shipping/:id', to: 'orders#shipping', as: :shipping
  get 'orders/payment/:id', to: 'orders#payment', as: :payment
end

app/models/user.rb
class User < ApplicationRecord
  # Relationships with other models
  has_many :designs
  has_many :articles
  has_many :addresses
  has_many :orders
  # Use friendly_id to generate user friendly urls
  extend FriendlyId
  friendly_id :first_name, use: [:slugged, :finders, :history]
  # Voting
  acts_as_voter
  # Add image uploader view
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  MALE = 'Male'
  FEMALE = 'Female'
  OTHER_GENDER = 'Gender Free'
  GENDERS = [MALE, FEMALE, OTHER_GENDER]

  validates :gender, inclusion: GENDERS, allow_blank: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.image = auth.info.image
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.location = auth.info.location
      user.description = auth.info.about
      user.gender = auth.extra.raw_info.gender.capitalize
      user.save!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  def is_admin?
    admin == true
  end

  def after_confirmation
    WelcomeMailer.signup_confirmation(self).deliver
  end

  def to_s
    "#{first_name} #{last_name}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    query = params[:search].to_s.downcase.presence
    if query
      @users = User.where('LOWER(first_name) LIKE ?', "%#{query}%").page(params[:page]).per(20)
    else
      @users = User.all.page(params[:page]).per(20)
    end
  end

  def show
    @user = User.friendly.find(params[:id])
    @notifications = Notification.where(user: @user).page(params[:page]).per(10)
    @designs = Design.where(user: @user).page(params[:page]).per(6)
    @articles = Article.where(user: @user).page(params[:page]).per(3)
  end

  def design
    @designs = Design.where(user: current_user).page(params[:page]).per(2)
  end

  def order
    @orders = current_user.orders.page(params[:page]).per(5)
  end

  def content
    @articles = Article.where(user: current_user).page(params[:page]).per(5)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/users/_add_design_button.html.erb
<!-- Button -->
<div class="buttons_design">
  <a  href="/designs" class="button button_blue button_become_left">
      <div class="button__text">Upload New Outfit</div>
  </a>
  <a href="<%= guide_path %>" class="button button_blue button_become_right">
      <div class="button__text">Competition Designer Guide</div>
  </a>
</div>
<!-- En Buttons Section -->

app/views/users/_edit_profile.html.erb
<%= form_for(resource, as: @user, url: registration_path(@user), html: { method: :put, class: "form account__form" }) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <p class="form__group">
      <%= f.label :email, class: "form__label form__label_required" %><br />
      <%= f.email_field :email, autofocus: true, class: "form__input" %>
    </p>
  </div><br>

  <div class="field">
    <p class="form__group">
      <%= f.label :first_name, class: "form__label form__label_required" %><br />
      <%= f.text_field :first_name, autofocus: true, class: "form__input" %>
    </p>
  </div><br>

  <div class="field">
    <p class="form__group">
      <%= f.label :last_name, class: "form__label form__label_required" %><br />
      <%= f.text_field :last_name, autofocus: true, class: "form__input" %>
    </p>
  </div><br>

  <div class="field">
    <p class="form__group">
      <%= f.label :phone_number, class: "form__label form__label_required" %><br />
      <%= f.text_field :phone_number, autofocus: true, class: "form__input" %>
    </p>
  </div><br>

  <div class="field">
    <p class="form__group">
      <%= f.label :description, class: "form__label form__label_required" %><br />
      <%= f.text_area :description, autofocus: true, class: "form__input" %>
    </p>
  </div><br>

  <div class="field">
    <p class="form__group">
      <%= f.label :gender, class: "form__label form__label_required" %><br />
      <%= f.select :gender, options_for_select(User::GENDERS), autofocus: true, class: "button button_blue" %>
    </p>
  </div><br />  

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <% if f.object.encrypted_password.present? %>
    <div class="field">
      <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
      <%= f.password_field :password, autocomplete: "off" %>
      <% if @minimum_password_length %>
        <br />
        <em><%= @minimum_password_length %> characters minimum</em>
      <% end %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
      <%= f.password_field :current_password, autocomplete: "off" %>
    </div>
  <% end %>

  <p class="form__group">
      <label class="form__label">Connect</label>
  </p>
  <div class="account__connect">
      <div class="account__connect-button">
          <div class="account__connect-icon"><i class="fa fa-facebook" aria-hidden="true"></i></div>
          <div class="account__connect-text"><input class="form__input" type="text" name="" value="" placeholder="Facebook user"></div>
      </div>
      <div class="account__connect-button">
          <div class="account__connect-icon"><i class="fa fa-twitter" aria-hidden="true"></i></div>
          <div class="account__connect-text"><input class="form__input" type="text" name="" value="" placeholder="Twitter user"></div>
      </div>
      <div class="account__connect-button">
          <div class="account__connect-icon"><i class="fa fa-google-plus" aria-hidden="true"></i></div>
          <div class="account__connect-text"><input class="form__input" type="text" name="" value="" placeholder="Google user"></div>
      </div>
      <div class="account__connect-button">
          <div class="account__connect-icon"><i class="fa fa-pinterest-p" aria-hidden="true"></i></div>
          <div class="account__connect-text"><input class="form__input" type="text" name="" value="" placeholder="Pinterest user"></div>
      </div>
      <div class="account__connect-button">
          <div class="account__connect-icon"><i class="fa fa-instagram" aria-hidden="true"></i></div>
          <div class="account__connect-text"><input class="form__input" type="text" name="" value="" placeholder="Instagram user"></div>
      </div>
      <div class="account__connect-button">
          <div class="account__connect-icon"><i class="fa fa-behance" aria-hidden="true"></i></div>
          <div class="account__connect-text"><input class="form__input" type="text" name="" value="" placeholder="Behance user"></div>
      </div>
  </div>
  <p></p>

  <div class="actions">
    <%= f.submit "Save", class: "button button_blue" %>
  </div><br />
<% end %>

app/views/users/_image_upload.html.erb
<%= form_for(resource, as: @user, url: registration_path(@user), html: { method: :put, class: "form account__form", multipart: true }) do |f| %>
 <%= devise_error_messages! %>
 <%= f.hidden_field :image_status, value: "upload" %>
 <p class="form__group">
  <%= f.file_field :avatar, class: "form__input" %>
 </p>
 <p class="form__group">
  <%= f.submit "Upload Photo", class: "button button_blue"%>
 </p>
<% end %>

app/views/users/_left_menu.html.erb
<!-- Left menu start -->
<ul class="left-menu">
   <li class="left-menu__item">
      <a class="left-menu__link" href="">
         <div class="left-menu__link-text">My feed</div>
         <div class="left-menu__link-arrow">
            <svg width="9" height="15" viewBox="0 0 9 15" xmlns="http://www.w3.org/2000/svg">
               <title>Fill 1</title>
               <path d="M8 7.38c.003.175-.08.33-.215.463l-2.162 2.16c-1.156 1.156-2.312 2.31-3.466 3.467-.14.14-.292.246-.5.246-.267 0-.508-.144-.6-.378-.104-.26-.068-.503.13-.706.287-.294.58-.58.87-.87C3.49 10.326 4.924 8.89 6.358 7.46c.098-.1.098-.1 0-.2-1.713-1.71-3.425-3.423-5.14-5.134-.128-.13-.212-.275-.215-.462-.005-.282.125-.482.372-.603.233-.113.515-.064.707.124.275.267.544.54.816.812l4.883 4.882c.135.134.22.288.217.5" stroke="currentColor" fill="currentColor" fill-rule="evenodd"/>
            </svg>
         </div>
      </a>
   </li>
   <li class="left-menu__item">
      <a class="left-menu__link" href="<%= user_orders_path id: current_user.slug %>">
         <div class="left-menu__link-text">My orders</div>
         <div class="left-menu__link-arrow">
            <svg width="9" height="15" viewBox="0 0 9 15" xmlns="http://www.w3.org/2000/svg">
               <title>Fill 1</title>
               <path d="M8 7.38c.003.175-.08.33-.215.463l-2.162 2.16c-1.156 1.156-2.312 2.31-3.466 3.467-.14.14-.292.246-.5.246-.267 0-.508-.144-.6-.378-.104-.26-.068-.503.13-.706.287-.294.58-.58.87-.87C3.49 10.326 4.924 8.89 6.358 7.46c.098-.1.098-.1 0-.2-1.713-1.71-3.425-3.423-5.14-5.134-.128-.13-.212-.275-.215-.462-.005-.282.125-.482.372-.603.233-.113.515-.064.707.124.275.267.544.54.816.812l4.883 4.882c.135.134.22.288.217.5" stroke="currentColor" fill="currentColor" fill-rule="evenodd"/>
            </svg>
         </div>
      </a>
   </li>
   <li class="left-menu__item">
      <a class="left-menu__link" href="<%= user_designs_path id: current_user.slug %>">
         <div class="left-menu__link-text">My designs</div>
         <div class="left-menu__link-arrow">
            <svg width="9" height="15" viewBox="0 0 9 15" xmlns="http://www.w3.org/2000/svg">
               <title>Fill 1</title>
               <path d="M8 7.38c.003.175-.08.33-.215.463l-2.162 2.16c-1.156 1.156-2.312 2.31-3.466 3.467-.14.14-.292.246-.5.246-.267 0-.508-.144-.6-.378-.104-.26-.068-.503.13-.706.287-.294.58-.58.87-.87C3.49 10.326 4.924 8.89 6.358 7.46c.098-.1.098-.1 0-.2-1.713-1.71-3.425-3.423-5.14-5.134-.128-.13-.212-.275-.215-.462-.005-.282.125-.482.372-.603.233-.113.515-.064.707.124.275.267.544.54.816.812l4.883 4.882c.135.134.22.288.217.5" stroke="currentColor" fill="currentColor" fill-rule="evenodd"/>
            </svg>
         </div>
      </a>
   </li>
   <li class="left-menu__item">
      <a class="left-menu__link" href="<%= user_content_path id: current_user.slug %>">
         <div class="left-menu__link-text">My content</div>
         <div class="left-menu__link-arrow">
            <svg width="9" height="15" viewBox="0 0 9 15" xmlns="http://www.w3.org/2000/svg">
               <title>Fill 1</title>
               <path d="M8 7.38c.003.175-.08.33-.215.463l-2.162 2.16c-1.156 1.156-2.312 2.31-3.466 3.467-.14.14-.292.246-.5.246-.267 0-.508-.144-.6-.378-.104-.26-.068-.503.13-.706.287-.294.58-.58.87-.87C3.49 10.326 4.924 8.89 6.358 7.46c.098-.1.098-.1 0-.2-1.713-1.71-3.425-3.423-5.14-5.134-.128-.13-.212-.275-.215-.462-.005-.282.125-.482.372-.603.233-.113.515-.064.707.124.275.267.544.54.816.812l4.883 4.882c.135.134.22.288.217.5" stroke="currentColor" fill="currentColor" fill-rule="evenodd"/>
            </svg>
         </div>
      </a>
   </li>
   <li class="left-menu__item">
      <a class="left-menu__link left-menu__link_selected" href="<%= user_path current_user.slug %>">
         <div class="left-menu__link-text" id="account">Account settings</div>
         <div class="left-menu__link-arrow">
            <svg width="9" height="15" viewBox="0 0 9 15" xmlns="http://www.w3.org/2000/svg">
               <title>Fill 1</title>
               <path d="M8 7.38c.003.175-.08.33-.215.463l-2.162 2.16c-1.156 1.156-2.312 2.31-3.466 3.467-.14.14-.292.246-.5.246-.267 0-.508-.144-.6-.378-.104-.26-.068-.503.13-.706.287-.294.58-.58.87-.87C3.49 10.326 4.924 8.89 6.358 7.46c.098-.1.098-.1 0-.2-1.713-1.71-3.425-3.423-5.14-5.134-.128-.13-.212-.275-.215-.462-.005-.282.125-.482.372-.603.233-.113.515-.064.707.124.275.267.544.54.816.812l4.883 4.882c.135.134.22.288.217.5" stroke="currentColor" fill="currentColor" fill-rule="evenodd"/>
            </svg>
         </div>
      </a>
   </li>
   <li class="left-menu__item">
      <a class="left-menu__link" href="<%= user_address_path current_user.slug %>">
         <div class="left-menu__link-text">Shipping address</div>
         <div class="left-menu__link-arrow">
            <svg width="9" height="15" viewBox="0 0 9 15" xmlns="http://www.w3.org/2000/svg">
               <title>Fill 1</title>
               <path d="M8 7.38c.003.175-.08.33-.215.463l-2.162 2.16c-1.156 1.156-2.312 2.31-3.466 3.467-.14.14-.292.246-.5.246-.267 0-.508-.144-.6-.378-.104-.26-.068-.503.13-.706.287-.294.58-.58.87-.87C3.49 10.326 4.924 8.89 6.358 7.46c.098-.1.098-.1 0-.2-1.713-1.71-3.425-3.423-5.14-5.134-.128-.13-.212-.275-.215-.462-.005-.282.125-.482.372-.603.233-.113.515-.064.707.124.275.267.544.54.816.812l4.883 4.882c.135.134.22.288.217.5" stroke="currentColor" fill="currentColor" fill-rule="evenodd"/>
            </svg>
         </div>
      </a>
   </li>
</ul>
<!-- Left menu finish -->

app/views/users/_my_designs.html.erb
<h3 class="title_h3">My designs</h3>
<!-- My designs start -->
<ul class="my-designs">
    <% @designs.each do |design| %>
    <li class="my-designs__item">
        <div class="my-designs__image-wrapper">
          <div class="my-designs__image" style="background-image: url('<%= asset_path design.image.url.to_s %>')"></div>
        </div>
        <div class="my-designs__info">
            <div class="my-designs__title">Description</div>
            <div class="my-designs__description"><%= design.image_desc %></div>
            <div class="my-designs__date">Submitted <%= design.created_at.strftime("%d %B %Y")%></div>
            <% unless design.in_competition? %>
            <div class="buttons_one_design">
              <a  href="/add-to-competition/<%= design.id %>" class="button_small button_blue button_design_right">
                  <div class="button__text">Add to Competition</div>
              </a>
            </div>
            <% end %>
    </li>
    <% end %>
</ul>
<!-- My designs finish -->

app/views/users/_profile.html.erb
<div class="columns__content">
   <h3 class="title_h3">My profile</h3>
   <!-- Account settings start -->
   <div class="account">
     <div class="">
        <div class="account__avatar">

          <% if @user.image_status == "upload" %>
             <div class="account__avatar-photo" style="background-image: url(<%= asset_path @user.avatar_url %>);"></div>
          <% elsif @user.image != nil%>
            <%= image_tag @user.image, class: "account__avatar-photo" %>
          <% else %>
            <div class="account__avatar-photo" ></div>
          <% end %>
          <br>
        </div>
        <div class="account__avatar-edit" id="edit-image">Upload Image</div>
         <!-- Image Upload-->
         <div id="upload-image">
            <%= render "image_upload" %>
         </div>
         <!-- End Image Upload -->
      </div>
      	<!-- Account settings start -->
	 	   <%= render "edit_profile" %>

      </form>
   </div>
   <!-- Account settings finish -->
</div>

app/views/users/_public_profile.html.erb
<div id="public_profile">
  <section class="user-info">
      <div class="dummy dummy__wrapper">
        <h3><%= @user.last_name %> <%= @user.first_name %></h3>
        <div class="image-wrapper">
          <% if @user.image_status == "upload" %>
             <div class="account__avatar-photo" style="background-image: url(<%= asset_path @user.avatar_url %>);"></div>
          <% elsif @user.image != nil%>
             <div class="account__avatar-photo" style="background-image: url(<%=  asset_path @user.avatar_url %>);"></div>
          <% else %>
            <div class="account__avatar-photo" ></div>
          <% end %>
        </div>
        <div class="user-info-text">
          <span>Location - <%= @user.location %> </span> <br>
          <span>Member since <%= @user.created_at.strftime("%dth-%B-%Y")%> </span>
          <br>

          <p><%= @user.description %>.</p>
        </div>
        <h4>Connect with <%= @user.first_name %></h4>
        <div class="header__social">
         <a class="header__social-link" href="https://www.facebook.com/XXX" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i> </a>
         <a class="header__social-link" href="https://twitter.com/XXX" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i> </a>
         <a class="header__social-link" href="https://plus.google.com/XXX" target="_blank"><i class="fa fa-google-plus" aria-hidden="true"></i> </a>
         <a class="header__social-link" href="https://pinterest.com/XXX" target="_blank"><i class="fa fa-pinterest-p" aria-hidden="true"></i> </a>
         <a class="header__social-link" href="https://www.instagram.com/XXX" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
      </div>
    </div>
  </section>
<div class="dummy">
  <div class="dummy__wrapper">

    <section class="designs">
      <h3>Designs</h3>
      <div class="digg_pagination">
        <div class="page_info">
          <%= paginate @designs %>
        </div>
      </div>
      <% if @designs.empty? %>
        <p> This user has no designs available </p>
      <% else %>
        <ul class="designs-wrapper">
          <% @designs.each do |design| %>
            <li class="designs">
              <a href="<%= design_path design.id %>">

                <div class="design-image" style="background-image: url(<%= asset_path design.image.url %>);"></div>

              </a>
            </li>
          <% end %>
        </ul>
      <% end %>
      <%= paginate @designs, :page_links => false %>
    </section>


    <section class="blog-posts">
      <h3>blog posts</h3>
      <div class="digg_pagination">
        <div class="page_info">
          <%= paginate @articles %>
        </div>
      </div>

      <% if @articles.empty? %>
        <p> This user has no blogpost available </p>
      <% else %>
        <ul>
          <% @articles.each do |article| %>
            <li>
              <a href="">
              <div class="image" style="background-image: url(<%= asset_path article.image.url %>);"></div>

              </a>
              <div class="blog-description">
                <h4><%= article.title %></h4>
                <span>By <a href="<%= user_path article.user.slug %>"><%= @user.last_name %> <%= @user.first_name %></a> · </span>
                <span><%= article.created_at.strftime("%d-%B-%Y")%></span>
                <p> <%= article.description[0,300]%>...
                <br><br>
                <a href="<%= article_path article.id %>" class="read-more">Continue reading »</a></p>
              </div>
            </li>
          <% end %>
        </ul>
      <% end %>
      <%= paginate @articles, :page_links => false %>
    </section>
  </div>
</div>

app/views/users/content.html.erb
<% if current_user %>
  <div class="container" id="my_profile">
    <h1 class="title_h1">My dashboard</h1>
    <p class="page-description">Welcome to your dashboard. You can set up your account, check your orders and manage your designs here.</p>

    <div class="columns">
      <!-- Left menu start -->
      <div class="columns__left-menu">
          <%= render "left_menu" %>
      </div>
      <!-- Left menu finish -->

      <!-- Render orders div start-->
      <!-- <div class="dummy"> -->
        <div class="dummy__wrapper">
          <section class="blog-posts">
            <div class="page_info">
              <%= paginate @articles %>
            </div><br>

            <h3>blog posts</h3><br>
            <% if @articles.empty? %>
              <p> This user has no blogpost available </p>
            <% else %>
              <ul>
                <% @articles.each do |article| %>
                    <div class="">
                      <h4>TITLE: <%= article.title %></h4><br>
                      <span>By <a href="<%= user_path article.user.slug %>"><%= current_user.last_name %> <%= current_user.first_name %></a> · </span>
                      <span><%= article.created_at.strftime("%d-%B-%Y")%></span><br><br>
                      <p> <%= article.description[0,300]%>...

                      <a href="<%= article_path article.id %>" class="read-more">Continue reading »</a></p>
                    </div>
                <% end %>
              </ul>
            <% end %>
            <%= paginate @articles %>
          </section>
        </div>
      <!-- </div> -->
      <!-- Render orders div end -->
    </div>
  </div>
<% end %>

app/views/users/design.html.erb
<% if current_user %>
  <div class="container" id="my_profile">
    <h1 class="title_h1">My dashboard</h1>
    <p class="page-description">Welcome to your dashboard. You can set up your account, check your orders and manage your designs here.</p>

    <div class="columns">
      <!-- Left menu start -->
      <div class="columns__left-menu">
          <%= render "left_menu" %>
      </div>
      <!-- Left menu finish -->

      <!-- Render designs div start-->
      <div id="design-info">
        <%= render 'add_design_button' %>
        <% if @designs.empty? %>
          <p class="button__text"> User has no designs </p>
        <% else %>
          <%= render 'my_designs' %>
        <%end%>
        <%= paginate @designs %>
      </div>
      <!-- Render designs div end -->
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="wrapper">
  <form action="/users" method="get">
    <div class="bar">
      <input class="search-page" type="search" name="search" placeholder="Search...">
    </div>
  </form>

  <ul class="users-list">
  	<% @users.each do |user| %>
  	  <li>
  	    <div class="user-image-wrapper">
  	    	<% if user.image_status == "upload" %>
            <div class="user-image" style="background-image: url(<%=  asset_path user.avatar_url %>);"></div>
  	    	<% elsif user.image != nil%>
            <div class="user-image" ></div>
  	    	<% else %>
          <div class="user-image" ></div>

  	    	<% end %>

  	    </div>
        <div class="user-details">
          <a href="<%= user_path user.slug %>"><%= user.first_name  %> <%= user.last_name  %> </a>
        </div>

  	  </li>
    <% end %>
  </ul>

  <%= paginate @users %>
</div>

app/views/users/order.html.erb
<% if current_user %>
  <div class="container" id="my_profile">
    <h1 class="title_h1">My dashboard</h1>
    <p class="page-description">Welcome to your dashboard. You can set up your account, check your orders and manage your designs here.</p>

    <div class="columns">
      <!-- Left menu start -->
      <div class="columns__left-menu">
          <%= render "left_menu" %>
      </div>
      <!-- Left menu finish --> 

      <!-- Render orders div start-->
      <div id="design-info">
        <% if @orders.empty? %>
          <p class="button__text"> You have no orders </p>
        <% else %>
          <div  class="columns__content">
            <div class="page_info">
              <%= paginate @orders %>
            </div>
            <h3 class="title_h3">My Orders</h3>
            <!-- My orders start -->
              <% @orders.each do |order| %>             
                <div class="container">
                  <p>Order Number: <%= order.order_number %> </p>
                  <p>Order Status: <%= order.status.gsub('_',' ').capitalize %> </p>
                </div>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal-<%= order.id %>">
                  View order items
                </button><br><br>
                <!-- End Button trigger modal -->
                <!-- Modal -->
                <div class="modal fade" id="myModal-<%= order.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Order list</h4>
                      </div>
                      <div class="modal-body">
                        <div class="container">
                          <p>Order Number: <%= order.order_number %> </p>
                          <p>Order Status: <%= order.status %> </p>
                          <p>Transaction Number: <%= order.transaction_id %> </p>
                        </div><br>
                        <div class="container">
                          <% order.order_items.each do |item| %>
                            <p>Item Name: <%= item.get_product.name %></p>
                            <p>Quantity: <%= item.quantity %></p>
                            <p>Color: <%= item.color %></p>
                            <p>Price: € <%= item.get_product.price %></p>
                          <% end %>
                        </div><br>
                        <div class="container">
                          <p>Sub Total: <%= order.sub_total %></p>                        
                          <p>Shipping Costs: € <%= order.shipping_cost %></p>
                          <p>Tax: € <%= order.vat %></p>
                          <p>Total: € <%= order.total_amount %></p>
                        </div>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- End Modal -->
              <% end %>
            <!-- My orders finish -->
          </div><br>
        <%end%>
        <%= paginate @orders %>
      </div>
      <!-- Render orders div end -->
    </div>
  </div>
<% end %>