config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', confirmations: 'confirmations' }

  resources :designs do
    member do
      put 'like', to: 'designs#upvote'
    end
  end

  resources :products do
    resources :order_items, only: [:create, :destroy]
  end

  resources :articles do
    member do
      put 'like', to: 'articles#upvote'
    end
  end

  resources :addresses
  resources :orders, only: [:index, :show]

  root to: 'home#index'

  get 'users/:id', to: 'users#show', as: :user
  get 'users/:id/designs/', to: 'users#design', as: :user_designs
  get 'users/:id/orders/', to: 'users#order', as: :user_orders
  get 'users/:id/content/', to: 'users#content', as: :user_content
  get 'users/:id/address/', to: 'addresses#index', as: :user_address

  get '/users', to: 'users#index', as: :users_default
  get '/leaderboard', to: 'home#leaderboard'
  get '/competition', to: 'home#competition'
  get '/contact', to: 'home#contact', as: :contact_us
  post '/contact', to: 'home#contact_us', as: :message
  get '/add-to-competition/:id', to: 'designs#add_to_competition'

  # These are static pages, not necessarily having a controller method for each:
  get '/themes', to: 'home#themes', as: :themes
  get '/guide', to: 'home#guide', as: :guide
  get '/about', to: 'home#about', as: :about
  get '/faq', to: 'home#faq', as: :faq
  get '/privacy', to: 'home#privacy', as: :privacy

  post '/checkout', to: 'orders#checkout', as: :checkout
  post 'orders/shipping/:id', to: 'orders#shipping', as: :shipping
  get 'orders/payment/:id', to: 'orders#payment', as: :payment
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  DESIGNS_PER_COMPETITION_PAGE = 5

  def index
  end

  def leaderboard
    designs = Design.for_competition
    @designs = designs.first(10).sort { |designA, designB| designB.votes_for.size <=> designA.votes_for.size }
  end

  def competition
    @designs = Design.for_competition.page(params[:page]).per(DESIGNS_PER_COMPETITION_PAGE)
  end

  def contact
    @message = Message.new
  end

  def contact_us
    @message = new_message
    if @message.save
      UserMailer.contact_us(@message).deliver
      redirect_to contact_us_path, notice: 'Message sent successfully'
    else
      render :contact, notice: 'Sorry, your message could not be sent. please try again'
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :message)
  end

  def new_message
    Message.new(message_params)
  end
  
end

app/views/home/competition.html.erb
<!-- Latest start -->
<section class="latest">
<div class="latest__wrapper">
  <div class="latest__title">Latest Competition Designs</div>
  <div class="latest__tile-list">
      <figure class="latest__tile">
        <div class="wrapper__image">
          <!-- <%= image_tag "_MG_6406.jpg", class: "latest__image" %> -->
          <div class="latest__image"  style="background-image: url(<%= asset_path '_MG_6406.jpg' %>) "></div>
          <figcaption class="latest__caption"><a class="latest__link" href="">Shana M. - Olive blouse shirt</a></figcaption>
        </div>
      </figure>
      <figure class="latest__tile">
        <div class="wrapper__image">
          <!-- <%= image_tag "_MG_6465.jpg", class: "latest__image second" %> -->
          <div class="latest__image second" style="background-image: url(<%= asset_path '_MG_6465.jpg' %>)" ></div>
          <figcaption class="latest__caption"><a class="latest__link" href="">Carolyn J. - Cashmere sweater</a></figcaption>
        </div>
      </figure>
  </div>

</div>
</section>
<!-- Latest finish -->
<!-- Call to action start -->
<div class="call-to-action">
    <div class="call-to-action__wrapper">
        <div class="call-to-action__title">Join the competition and become a Lumumba designer</div>
        <div class="call-to-action__text">If you win, your designs will become a Lumumba clothing collection. You create amazing designs, we take care of the rest</div>
        <a href="/designs" class="button button_white-blue">
            <div class="button__text">Become a Designer</div>
        </a>
    </div>
</div>
<!-- Call to action finish -->
<!-- Filter start -->
<div class="filter">
    <div class="filter__wrapper">
        <div class="filter__droprown">
            <div class="filter__droprown-title">Sort by</div>
            <select class="filter__droprown-select" name="sort">
                <option value="dresses" selected="selected">Dresses</option>
                <option value="t-shirts">T-Shirts</option>
            </select>
        </div>
        <div class="filter__droprown">
            <div class="filter__droprown-title">Filter</div>
            <select class="filter__droprown-select" name="filter">
                <option value="dresses" selected="selected">Dresses</option>
                <option value="t-shirts">T-Shirts</option>
            </select>
        </div>
        <div class="filter__summary"><%= paginate @designs %></div>
    </div>
</div>
<!-- Filter finish -->
<div class="contestants">
    <div class="contestants__wrapper">
        <ul class="contestants__list">
            <% @designs.each do |design| %>
            <li class="contestants__item">
                <a class="contestants__link" href="<%= design_path design.id %>">
                  <div class="contestants__photo" style="background-image: url(<%= asset_path design.image_url.to_s %>)" ></div>
                </a>
                <div class="contestants__info">
                    <div class="contestants__author">By <a class="contestants__author-link" href="<%= user_path design.user.slug %>"><%= design.user.first_name%> <%= design.user.last_name%></a></div>
                    <div class="contestants__action">
                        <%= link_to like_design_path(design), method: :put do %>
                           <svg width="22" height="20" viewBox="0 0 22 20" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
                                <title>Page 1</title>
                                <defs>
                                    <path id="like-path" d="M21.97 0H0v19.957h21.97V0z" />
                                </defs>
                                <g fill="none" fill-rule="evenodd" >
                                    <a xlink:href="/users/<%= design.user.slug%>/"></a>
                                    <path d="M1.005 5.418c-.008 1.135.215 1.885.5 2.62.35.89.806 1.733 1.315 2.547.997 1.596 2.168 3.062 3.473 4.428 1.38 1.446 2.88 2.757 4.588 3.83.08.05.134.044.21-.003.968-.603 1.868-1.293 2.722-2.04 1.56-1.364 2.955-2.877 4.184-4.533 1.035-1.394 1.955-2.852 2.56-4.48.19-.513.34-1.037.39-1.58.082-.882-.075-1.73-.494-2.517-.773-1.456-1.988-2.344-3.646-2.64-.766-.138-1.52-.084-2.265.135-1.064.312-1.93.903-2.586 1.778-.31.414-.59.85-.882 1.274-.083.12-.093.12-.172.005-.238-.347-.472-.697-.713-1.042-.9-1.287-2.133-2.032-3.728-2.197-.82-.085-1.62.02-2.367.343-1.954.846-2.966 2.337-3.088 4.072m20.964.295c-.034.97-.22 1.688-.48 2.392-.567 1.553-1.41 2.963-2.373 4.308-1.434 2.01-3.1 3.817-5 5.42-.84.708-1.725 1.36-2.67 1.932-.128.077-.27.132-.412.186-.04.017-.098 0-.143-.016-.327-.112-.606-.308-.89-.495-2.034-1.34-3.792-2.973-5.38-4.788C3.4 13.256 2.31 11.77 1.416 10.15 1.002 9.4.64 8.63.373 7.818.14 7.11-.037 6.386.007 5.636.147 3.31 1.303 1.622 3.424.574 4.338.122 5.33-.056 6.35.02c1.887.137 3.4.954 4.525 2.443.01.013.016.026.026.038.077.104.082.1.165.003.26-.3.506-.62.795-.893.71-.67 1.55-1.125 2.5-1.385.805-.22 1.622-.29 2.444-.16 2.136.337 3.688 1.458 4.626 3.367.387.788.544 1.627.54 2.28" fill="currentColor" />
                                </g>
                            </svg>
                        <% end %>
                    </div>
                    <div class="contestants__action">
                        <div class="">
                          <%= design.get_upvotes.size %>
                        </div>
                    </div>
                </div>
            </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/home/contact.html.erb
<div class="layout__content">
    <div class="wrapper">
        <h1 class="title_h1">Contact</h1>
        <p class="page-description">We are happy to talk to you. Feel free to contact us by email, WhatsApp or Facebook. We have a WhatsApp channel, you can text us and we'll add you to our Lumumba group</p>
        <!-- Contact start -->
        <div class="contact">
                <%= form_for :message ,url: message_path, html: {class: "form contact__form " } do |f| %> 
                  <% if @message.errors.any? %>
                    <div id="error_explanation">
                      <h2>
                        <%= pluralize(@message.errors.count, "error") %> prohibited
                        this message from being saved:
                      </h2>
                      <ul>
                        <% @message.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                  <p class="form__group">
                    <%= f.text_field :name, class: "form__input form__input_blue", placeholder: "Enter your name"%>
                  </p><br>

                  <p class="form__group">
                    <%= f.email_field :email, class: "form__input form__input_blue", placeholder: "Enter your email" %>
                  </p><br>

                  <p class="form__group">
                    <%= f.text_area :message,class: "form__input form__input_blue", placeholder: "Enter your message", rows: "5", cols: "58" %>
                  </p><br>

                  <p class="form__group">
                    <%= f.submit "Send", class: "button button_blue"%>
                  </p>
                <% end %>

                <div class="contact__info">
                <div class="contact__header">Main Office</div><address class="contact__text">Cloud Coworking<br>Sardenya 229<br>Barcelona, Spain<br><br>+34 629 075 292</address>
                <div class="contact__header">Connect with Lumumba</div>
                <div class="contact__social"><a class="contact__social-link" href="https://www.facebook.com/lumumbafashion/" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i> </a><a class="contact__social-link" href="https://twitter.com/lumumbafashion" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i> </a><a class="contact__social-link" href="https://pinterest.com/lumumbafashion" target="_blank"><i class="fa fa-pinterest-p" aria-hidden="true"></i> </a><a class="contact__social-link" href="https://www.instagram.com/lumumbafashion" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></div>
            </div>
        </div>
        <!-- Contact finish -->
    </div>
</div>

app/views/home/guide.html.erb
<!-- Section tittle -->
<h1 class="title_h1_head">Design Guide</h1>

<h4 class="links_guide"><a href="#step1">1. WHO CAN BE PART OF THE COMPETITION?</a></h4>
<h4 class="links_guide"><a href="#step2">2. HOW DOES IT WORK?</a></h4>
<h4 class="links_guide"><a href="#step3">3. WHAT DO I HAVE TO DELIVER TO COMPETE?</a></h4>
<h4 class="links_guide"><a href="#step4">4. WHAT DO I HAVE TO DESIGN AND FOR WHOM? FOR WHICH SEASON?</a></h4>
<h4 class="links_guide"><a href="#step5">5. WHAT MATERIALS CAN I USE?</a></h4>
<h4 class="links_guide"><a href="#step6">6. WHAT ARE THE DATES?</a></h4>
<h4 class="links_guide"><a href="#step7">7. WHAT IS THE PRIZE?</a></h4>
<!-- End Section tittle -->

<div class="wrapper">
  <h1 id="step1" class="title_h1_guide">1.Who can be part of the competition?</h1>

  <p class="paragraph_guide paragraph_orange">Everybody in the world! You just need to present the designs in digital format or as pictures with a model and prototype.</p>

  <h1 id="step2" class="title_h1_guide">2. How does it works?</h1>
  <p class="paragraph_guide paragraph_red">Welcome to the Lumumba tribe. Each month of the year we select a different culture from the world and we will host an online design competition. The competition will follow the monthly cultural theme. We will write stories about it, publish pictures, videos and such, so you can learn about it and get inspiration.
    <br />
      You can visit <a href="<%= themes_path %>">Theme page</a> on the website where you can find information describing the culture and theme of the competition. Inside your profile, you can upload designs anytime you want. Designs can be edited, uploaded to the competition and much more through your profile. Imagine as if you have your own Lumumba portfolio.
    <br />
      We want you to be part of the community and join us on this journey. If you want to win the competition, you will need to obtain the most votes. So feel free to ask your friends and family to vote for you. We want to promote local talent around the world, this is an opportunity for you to start spreading your designs and ideas internationally.
  </p>

  <h1 id="step3" class="title_h1_guide">3. What do I have to deliver to compete? </h1>
  <p class="paragraph_guide paragraph_blue">An outfit for women consisting of three pieces of garment. You will have to upload 5 JPG file and describe your inspiration for each design. You also have the option to upload the Technical Sheet.
    <br />
    Optional: You can prototype the garments and send pictures with models (ask your friends!). The better the presentation is, the better the response will be from the Lumumba tribe.
  </p>

  <h1 id="step4" class="title_h1_guide">4. What do I have to design and for whom? For which season?</h1>

  <p class="paragraph_guide paragraph_orange">We would like the clothes to be street, modern and urban, so anybody in any city can wear them on a daily basis. The clothing collection made by the competition's winner will be released 2-3 months after the end of the competition. You should take into account the seasonality (Spring - Summer - Autumn - Winter). This means, if the competition is held in December, the clothing collection will be released during February, which is late Winter - early Spring.</p>

  <h1 id="step5" class="title_h1_guide">5. What materials can I use?</h1>

  <p class="paragraph_guide paragraph_red">We will produce the garments under your specifications. Try to use common materials so that the final garment can be the same as your designs. We can use digital printing, embroidery and other basic techniques. Avoid metal, mirror and hand-made materials with difficult applications.  </p>

  <h1 id="step6" class="title_h1_guide">6. What are the dates?</h1>

  <p class="paragraph_guide paragraph_blue">Each competition lasts a complete month, from January to December. We open a total of 12 competitions each year inspired by 12 different cultures.</p>

  <h1 id="step7"class="title_h1_guide">7. What is the prize?</h1>

  <div class="paragraph_guide paragraph_orange">
    <ul>
      <li class="li_guide">
        10% of the net income (Revenue of your clothes - Cost of your clothes). The winners will be showcased on the platform and our social media profiles.
      </li>
      <li class="li_guide">
        We will interview them and create content with their ideas. They will also be invited to publish content on the platform.
      </li>
      <li class="li_guide">
        The clothes will be sold internationally and the label will feature your name like this: "Your Name x Lumumba".
      </li>
    </ul>
  </div>

  <center>
    <a href="/designs" class="button button_orange">
        <div class="button__text">Get Started</div>
    </a>
  </center>
</div>

app/views/home/index.html.erb
<section id="sign-in" >

  <div class="image column" style="background-image: url(<%= asset_path 'home.jpg' %>)">
    <div class="columns__content">
        <h1 class="">Diverse Multicultural Fashion </h1>
        <h1 class="">Wear the World.</h1>
    </div>
  </div>

  <div class="form column" style="background-image: url(<%= asset_path 'home_bg.png' %>)">
    <div class="columns__content">
      <!-- Section tittle -->
        <h2 class="">Join Lumumba</h1>

      <!-- End Section tittle -->
      <!-- START Botones sociales -->
      <a href="/users/auth/facebook">
        <div class="button-social facebook">
        <i class="fa fa-facebook" aria-hidden="true"></i> <spam class="social-text">Sign up using Facebook</spam>
      </div>
      </a>
      <a href="/">
      <div class="button-social twitter">
        <i class="fa fa-twitter" aria-hidden="true"></i> <spam class="social-text">Sign up using Twitter</spam>
      </div>
      </a>
      <a href="/">
      <div class="button-social google">
        <i class="fa fa-google-plus" aria-hidden="true"></i> <spam class="social-text">Sign up using Google+</spam>
      </div>
      </a>
      <!-- END Botones sociales -->
        <p class="page-description_social">By signing up you agree to the <a href="#"> Terms of Services</a> and <a href="#">Privacy Policy</a> </p>
    </div>
  </div>
</section>

<section id="collection" style="background-image: url(<%= asset_path 'latest_bg.png' %>)">
<div class="latest__wrapper">
  <div class="logos">
    <div class="right">
      <%= image_tag "lumumbalogo_white2.png", class: "img_responsive" %>

    </div>
    <div class="left">
      <%= image_tag "masabalogo_white.png", class: "img_responsive" %>

    </div>



  </div>
  <div class="latest__title">Masaba x Lumumba</div>
  <div class="latest__tile-list">
      <figure class="latest__tile">
        <div class="wrapper__image">
          <div class="latest__image" style="background-image: url(<%= asset_path '_MG_6406.jpg' %>) "></div>
          <figcaption class="latest__caption"><a class="latest__link" href="product.html">Shana M. - Olive blouse shirt</a></figcaption>
        </div>
      </figure>
      <figure class="latest__tile">
        <div class="wrapper__image">
          <div class="latest__image second" style="background-image: url(<%= asset_path '_MG_6465.jpg' %>)" ></div>
          <figcaption class="latest__caption"><a class="latest__link" href="product.html">Carolyn J. - Cashmere sweater</a></figcaption>
        </div>
      </figure>
  </div>
  <div class="bottom">
    <a class="latest__link button" href="<%= products_path %>">See more products</a>
  </div>

</div>
</section>

<section id="competition" style="background-image: url(<%= asset_path 'countdown_bg.png' %>)">
  <div class="call-to-action">
    <div class="call-to-action__wrapper">
        <div class="call-to-action__title">The Competition is Live Now.</div>
        <div class="call-to-action__text">Want to join the Lumumba tribe? Get inspired by the Banjara and create a street fashion outfit for the competition.</div>
        <a href="/designs" class="button ">
            <div class="button__text">Become a Designer</div>
        </a>
    </div>
  </div>
</section>

app/views/home/leaderboard.html.erb
<div class="wrapper" id="leaderboard">
    <h1 class="title_h1">Leaderboard</h1>
    <p class="page-description">Discover who is who in the Lumumba community. Are you part of the competition? You can check here how many votes you have and how well you are doing.</p>
    <div class="columns">
        <div class="columns__left-menu">
            <!-- Left menu start -->
            <ul class="left-menu">
              <li class="left-menu__item">
                  <a class="left-menu__link left-menu__link_selected"  data-tab="trending" >
                      <div class="left-menu__link-text">Trending This Week</div>
                      <div class="left-menu__link-arrow">
                          <svg width="9" height="15" viewBox="0 0 9 15" xmlns="http://www.w3.org/2000/svg">
                              <title>Fill 1</title>
                              <path d="M8 7.38c.003.175-.08.33-.215.463l-2.162 2.16c-1.156 1.156-2.312 2.31-3.466 3.467-.14.14-.292.246-.5.246-.267 0-.508-.144-.6-.378-.104-.26-.068-.503.13-.706.287-.294.58-.58.87-.87C3.49 10.326 4.924 8.89 6.358 7.46c.098-.1.098-.1 0-.2-1.713-1.71-3.425-3.423-5.14-5.134-.128-.13-.212-.275-.215-.462-.005-.282.125-.482.372-.603.233-.113.515-.064.707.124.275.267.544.54.816.812l4.883 4.882c.135.134.22.288.217.5" stroke="currentColor" fill="currentColor" fill-rule="evenodd" />
                          </svg>
                      </div>
                  </a>
              </li>
              <li class="left-menu__item">
                  <a class="left-menu__link" data-tab="competition_lead">
                      <div class="left-menu__link-text">Current Competition Leaders</div>
                      <div class="left-menu__link-arrow">
                          <svg width="9" height="15" viewBox="0 0 9 15" xmlns="http://www.w3.org/2000/svg">
                              <title>Fill 1</title>
                              <path d="M8 7.38c.003.175-.08.33-.215.463l-2.162 2.16c-1.156 1.156-2.312 2.31-3.466 3.467-.14.14-.292.246-.5.246-.267 0-.508-.144-.6-.378-.104-.26-.068-.503.13-.706.287-.294.58-.58.87-.87C3.49 10.326 4.924 8.89 6.358 7.46c.098-.1.098-.1 0-.2-1.713-1.71-3.425-3.423-5.14-5.134-.128-.13-.212-.275-.215-.462-.005-.282.125-.482.372-.603.233-.113.515-.064.707.124.275.267.544.54.816.812l4.883 4.882c.135.134.22.288.217.5" stroke="currentColor" fill="currentColor" fill-rule="evenodd" />
                          </svg>
                      </div>
                  </a>
              </li>
              <li class="left-menu__item">
                  <a class="left-menu__link" data-tab="winners">
                      <div class="left-menu__link-text">Past Winners</div>
                      <div class="left-menu__link-arrow">
                          <svg width="9" height="15" viewBox="0 0 9 15" xmlns="http://www.w3.org/2000/svg">
                              <title>Fill 1</title>
                              <path d="M8 7.38c.003.175-.08.33-.215.463l-2.162 2.16c-1.156 1.156-2.312 2.31-3.466 3.467-.14.14-.292.246-.5.246-.267 0-.508-.144-.6-.378-.104-.26-.068-.503.13-.706.287-.294.58-.58.87-.87C3.49 10.326 4.924 8.89 6.358 7.46c.098-.1.098-.1 0-.2-1.713-1.71-3.425-3.423-5.14-5.134-.128-.13-.212-.275-.215-.462-.005-.282.125-.482.372-.603.233-.113.515-.064.707.124.275.267.544.54.816.812l4.883 4.882c.135.134.22.288.217.5" stroke="currentColor" fill="currentColor" fill-rule="evenodd" />
                          </svg>
                      </div>
                  </a>
              </li>
              <li class="left-menu__item">
                  <a class="left-menu__link" data-tab="top_contributors">
                      <div class="left-menu__link-text">Top Lumumba Contributors</div>
                      <div class="left-menu__link-arrow">
                          <svg width="9" height="15" viewBox="0 0 9 15" xmlns="http://www.w3.org/2000/svg">
                              <title>Fill 1</title>
                              <path d="M8 7.38c.003.175-.08.33-.215.463l-2.162 2.16c-1.156 1.156-2.312 2.31-3.466 3.467-.14.14-.292.246-.5.246-.267 0-.508-.144-.6-.378-.104-.26-.068-.503.13-.706.287-.294.58-.58.87-.87C3.49 10.326 4.924 8.89 6.358 7.46c.098-.1.098-.1 0-.2-1.713-1.71-3.425-3.423-5.14-5.134-.128-.13-.212-.275-.215-.462-.005-.282.125-.482.372-.603.233-.113.515-.064.707.124.275.267.544.54.816.812l4.883 4.882c.135.134.22.288.217.5" stroke="currentColor" fill="currentColor" fill-rule="evenodd" />
                          </svg>
                      </div>
                  </a>
              </li>
            </ul>
            <!-- Left menu finish -->
        </div>


        <div class="columns__content active" id="trending">
            <h3 class="title_h3">TRENDING THIS WEEK</h3>
            <!-- Past winners start -->
            <ol class="past-winners">
              <% @designs.each do |design| %>
                <li class="past-winners__item">
                  <div class="top-designers__photo-wrapper">
                    <% if design.user.image_status == "upload" %>
                      <div class="top-designers__photo" style="background-image: url(<%= asset_path design.user.avatar_url %>);"></div>
                    <% elsif design.user.image != nil%>
                      <div class="top-designers__photo" style="background-image: url(<%= asset_path design.user.avatar_url %>);"></div>
                    <% else  %>
                      <div class="top-designers__photo" style="background-image: url(<%= asset_path 'default-user.png' %>);"></div>
                    <% end %>
                  </div>
                    <div class="past-winners__info">
                        <div class="past-winners__name"><%= design.user.first_name%> <%= design.user.last_name%></div>
                        <div class="past-winners__location"><%= design.user.location %></div>
                    </div>
                    <div class="past-winners__wins"> 34 competitions wins </div>
                    <div class="past-winners__earned">$ 192,383 total earned</div>
                </li>
              <% end %>
            </ol>
            <!-- Past winners finish -->
          </div>
        <div class="columns__content" id="competition_lead">
            <h3 class="title_h3">Current Competition Leaders</h3>
            <!-- Top designers start -->
            <ol class="top-designers">
              <% @designs.each do |design| %>
                <li class="top-designers__item">
                    <a class="top-designers__link" href="<%= user_path design.user.slug %>">
                        <div class="top-designers__project-wrapper">
                          <div class="top-designers__project" style="background-image: url(<%= asset_path design.image_url %>);"></div>
                        </div>

                        <div class="top-designers__photo-wrapper">
                          <% if design.user.image_status == "upload" %>
                            <div class="top-designers__photo" style="background-image: url(<%= asset_path design.user.avatar_url %>);"></div>
                          <% elsif design.user.image != nil%>
                            <div class="top-designers__photo" style="background-image: url(<%= asset_path design.user.avatar_url %>);"></div>
                          <% else  %>
                            <div class="top-designers__photo" style="background-image: url(<%= asset_path 'default-user.png' %>);"></div>
                          <% end %>
                        </div>

                        <div class="top-designers__info">
                            <div class="top-designers__name"><%= design.user.first_name%> <%= design.user.last_name%></div>
                            <div class="top-designers__location"><%= design.user.location %></div>
                            <div class="top-designers__location">Total Votes: <%= design.votes_for.size%></div>
                        </div>
                    </a>
                </li>
              <% end %>
            </ol>
          </div>

          <div class="columns__content" id="winners">
              <h3 class="title_h3">Past winners</h3>
              <!-- Past winners start -->
              <ol class="past-winners">
                <% @designs.each do |design| %>
                  <li class="past-winners__item">
                    <div class="top-designers__photo-wrapper">
                      <% if design.user.image_status == "upload" %>
                        <div class="top-designers__photo" style="background-image: url(<%= asset_path design.user.avatar_url %>);"></div>
                      <% elsif design.user.image != nil%>
                        <div class="top-designers__photo" style="background-image: url(<%= asset_path design.user.avatar_url %>);"></div>
                      <% else  %>
                        <div class="top-designers__photo" style="background-image: url(<%= asset_path 'default-user.png' %>);"></div>
                      <% end %>
                    </div>
                      <div class="past-winners__info">
                          <div class="past-winners__name"><%= design.user.first_name%> <%= design.user.last_name%></div>
                          <div class="past-winners__location"><%= design.user.location %></div>
                      </div>

                      <div class="past-winners__earned">$ 192,383 total earned</div>
                  </li>
                <% end %>
              </ol>
              <!-- Past winners finish -->
          </div>
          <div class="columns__content" id="top_contributors">
              <h3 class="title_h3">Top Lumumba contributors</h3>
              <!-- Top buyers start -->
              <ol class="top-buyers">
                <% @designs.each do |design| %>
                  <li class="past-winners__item">
                    <div class="top-designers__photo-wrapper">
                      <% if design.user.image_status == "upload" %>
                        <div class="top-designers__photo" style="background-image: url(<%= asset_path design.user.avatar_url %>);"></div>
                      <% elsif design.user.image != nil%>
                        <div class="top-designers__photo" style="background-image: url(<%= asset_path design.user.avatar_url %>);"></div>
                      <% else  %>
                        <div class="top-designers__photo" style="background-image: url(<%= asset_path 'default-user.png' %>);"></div>
                      <% end %>
                    </div>
                      <div class="past-winners__info">
                          <div class="past-winners__name"><%= design.user.first_name%> <%= design.user.last_name%></div>
                          <div class="past-winners__location"><%= design.user.location %></div>
                      </div>

                      <div class="past-winners__earned">$ 192,383 total earned</div>
                  </li>
                <% end %>

              </ol>
              <!-- Top buyers finish -->
          </div>


        </div>

</div>

app/views/home/privacy.html.erb
<h3>Coming soon</h3>